"""Default rules for CodeBundle exports."""

from __future__ import annotations

DEFAULT_OUTPUT_NAME = "codebundle-output.md"

DEFAULT_EXCLUDES: tuple[str, ...] = (
    ".git/**",
    "node_modules/**",
    "dist/**",
    "build/**",
    ".next/**",
    "coverage/**",
    "__pycache__/**",
    ".venv/**",
    "venv/**",
    "target/**",
    "out/**",
    ".idea/**",
    ".vscode/**",
    "*.pyc",
    "*.class",
    "*.jar",
    "*.war",
    "*.zip",
    "*.tar",
    "*.gz",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.webp",
    "*.ico",
    "*.pdf",
    "*.mp4",
    "*.mov",
    "*.mp3",
    "*.wav",
    ".env",
    ".env.*",
    "*.pem",
    "*.key",
    "*.p12",
    "*.keystore",
    "credentials.json",
    "service-account.json",
    "codebundle-output.md",
    "codebundle-output.txt",
    "*.codebundle.tmp.json",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
)
